version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: escola_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: escola_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
  api:
    build:
      context: ./api
    container_name: php_api_web 
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - mysql_db
    environment:
      DB_HOST: mysql_db 
      DB_NAME: escola_db      
      DB_USER: root         
      DB_PASS: admin123     
    restart: always

volumes:
  mysql_data: