CREATE DATABASE IF NOT EXISTS `escola_db`;
USE `escola_db`;

CREATE TABLE IF NOT EXISTS `Aluno` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `nome` VARCHAR(255) NOT NULL,
    `data_nascimento` DATE NOT NULL,
    `cpf` VARCHAR(14) NOT NULL UNIQUE, 
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `senha` VARCHAR(255) NOT NULL, 
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `Turma` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `nome` VARCHAR(255) NOT NULL,
    `descricao` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `Matricula` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `aluno_id` INT NOT NULL,
    `turma_id` INT NOT NULL,
    `data_matricula` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`aluno_id`) REFERENCES `Aluno`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`turma_id`) REFERENCES `Turma`(`id`) ON DELETE CASCADE,
    UNIQUE (`aluno_id`, `turma_id`) 
);

CREATE TABLE IF NOT EXISTS `User` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL, 
    `email` VARCHAR(255) UNIQUE,
    `role` VARCHAR(50) DEFAULT 'admin', 
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);